language: php

php:
  - 5.5

env:
  - SYMFONY_VERSION=2.7.*

before_script:
  - travis_retry composer self-update
  - composer require --prefer-source --dev symfony/symfony:${SYMFONY_VERSION}

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover
  - mkdir -p build/logs
   
after_script:
 - php vendor/bin/coveralls -v
